spring.application.name=WhatsAppChatBot
server.port=8080

logging.level.com.chatbot=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false